from PyQt5 import QtCore, QtGui, QtWidgets
import initrequests

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uri = QtWidgets.QLineEdit(self.centralwidget)
        self.uri.setGeometry(QtCore.QRect(30, 90, 481, 16))
        self.uri.setObjectName("uri")
        self.urlLabel = QtWidgets.QLabel(self.centralwidget)
        self.urlLabel.setGeometry(QtCore.QRect(30, 60, 131, 20))
        self.urlLabel.setObjectName("urlLabel")
        self.headerTitle = QtWidgets.QLabel(self.centralwidget)
        self.headerTitle.setGeometry(QtCore.QRect(30, 120, 111, 20))
        self.headerTitle.setObjectName("headerTitle")
        self.cookie = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.cookie.setGeometry(QtCore.QRect(30, 370, 481, 121))
        self.cookie.setObjectName("cookie")
        self.cookieTitle = QtWidgets.QLabel(self.centralwidget)
        self.cookieTitle.setGeometry(QtCore.QRect(30, 340, 101, 21))
        self.cookieTitle.setObjectName("cookieTitle")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(10, 10, 961, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Title.setFont(font)
        self.Title.setAutoFillBackground(False)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.radioGET = QtWidgets.QRadioButton(self.centralwidget)
        self.radioGET.setGeometry(QtCore.QRect(540, 108, 61, 31))
        self.radioGET.setObjectName("radioGET")
        self.radioPOST = QtWidgets.QRadioButton(self.centralwidget)
        self.radioPOST.setGeometry(QtCore.QRect(620, 108, 61, 31))
        self.radioPOST.setObjectName("radioPOST")
        self.radioPUT = QtWidgets.QRadioButton(self.centralwidget)
        self.radioPUT.setGeometry(QtCore.QRect(700, 108, 61, 31))
        self.radioPUT.setObjectName("radioPUT")
        self.radioDELETE = QtWidgets.QRadioButton(self.centralwidget)
        self.radioDELETE.setGeometry(QtCore.QRect(880, 110, 61, 31))
        self.radioDELETE.setObjectName("radioDELETE")
        self.requestBody = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.requestBody.setGeometry(QtCore.QRect(540, 188, 401, 81))
        self.requestBody.setObjectName("requestBody")
        self.putPostTitle = QtWidgets.QLabel(self.centralwidget)
        self.putPostTitle.setGeometry(QtCore.QRect(540, 158, 391, 21))
        self.putPostTitle.setObjectName("putPostTitle")
        self.reqCountLabel = QtWidgets.QLabel(self.centralwidget)
        self.reqCountLabel.setGeometry(QtCore.QRect(540, 280, 101, 21))
        self.reqCountLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.reqCountLabel.setObjectName("reqCountLabel")
        self.requestCount = QtWidgets.QSpinBox(self.centralwidget)
        self.requestCount.setGeometry(QtCore.QRect(540, 310, 101, 22))
        self.requestCount.setMinimum(1)
        self.requestCount.setMaximum(9999)
        self.requestCount.setObjectName("requestCount")
        self.cusVarLabel = QtWidgets.QLabel(self.centralwidget)
        self.cusVarLabel.setGeometry(QtCore.QRect(670, 280, 271, 51))
        self.cusVarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cusVarLabel.setWordWrap(True)
        self.cusVarLabel.setObjectName("cusVarLabel")
        self.customVars = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.customVars.setGeometry(QtCore.QRect(540, 388, 401, 101))
        self.customVars.setObjectName("customVars")
        self.cookieLabel = QtWidgets.QLabel(self.centralwidget)
        self.cookieLabel.setGeometry(QtCore.QRect(540, 350, 401, 21))
        self.cookieLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cookieLabel.setObjectName("cookieLabel")
        self.submitRequest = QtWidgets.QPushButton(self.centralwidget)
        self.submitRequest.setGeometry(QtCore.QRect(30, 502, 911, 51))
        self.submitRequest.clicked.connect(lambda:initrequests.request.button_pressed(self.uri.text(), 
        self.requestCount.value(), self.headers.toPlainText(), self.cookie.toPlainText(), self.requestBody.toPlainText(), 
        self.customVars.toPlainText(), 
        {"GET": self.radioGET.isChecked(), "POST": self.radioPOST.isChecked(), "PUT": self.radioPUT.isChecked(), "DELETE": self.radioDELETE.isChecked(), "PATCH": self.radioPATCH.isChecked()}))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.submitRequest.setFont(font)
        self.submitRequest.setObjectName("submitRequest")
        self.headers = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.headers.setGeometry(QtCore.QRect(30, 150, 481, 181))
        self.headers.setObjectName("headers")
        self.radioPATCH = QtWidgets.QRadioButton(self.centralwidget)
        self.radioPATCH.setGeometry(QtCore.QRect(780, 110, 61, 31))
        self.radioPATCH.setObjectName("radioPATCH")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 977, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.urlLabel.setText(_translate("MainWindow", "Enter URI + Parameters"))
        self.headerTitle.setText(_translate("MainWindow", "Enter Headers"))
        self.cookieTitle.setText(_translate("MainWindow", "Enter Cookie"))
        self.Title.setText(_translate("MainWindow", "HTTP Crafting"))
        self.radioGET.setText(_translate("MainWindow", "GET"))
        self.radioPOST.setText(_translate("MainWindow", "POST"))
        self.radioPUT.setText(_translate("MainWindow", "PUT"))
        self.radioDELETE.setText(_translate("MainWindow", "DELETE"))
        self.putPostTitle.setText(_translate("MainWindow", "POST / PUT / PATCH Body"))
        self.reqCountLabel.setText(_translate("MainWindow", "Number of Requests"))
        self.cusVarLabel.setText(_translate("MainWindow", "If Custom variables entered below, the number of requests is ignored in place of start, stop and stepping in custom variables json"))
        self.cookieLabel.setText(_translate("MainWindow", "Enter Custom Variables + Start/Stop Count - JSON Format"))
        self.submitRequest.setText(_translate("MainWindow", "Send Request/s"))
        self.radioPATCH.setText(_translate("MainWindow", "PATCH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

